Algoritmo "media_ponderada"
// 
//  
Var
x, y, z, media: real
 n, i: inteiro


Inicio

    escreva("Quantos casos voce vai digitar?")
    leia(n)
    
    para i de 1 ate n faca
    
       escreval("Digite tres numeros:")
          leia(x)
          leia(y)
          leia(z)

          media <- (x * 2 + y * 3 + z * 5) / 10
         
       escreval("MEDIA =", media:4:1)

 fimpara
       


        
       
Fimalgoritmo