Algoritmo "pares_consecutivos"
// 
//  
Var

   X, soma: inteiro
   
Inicio

   escreva("Digite um numero inteiro:")
   leia(X)
   
   enquanto X <> 0 faca
   
      se X % 2 <> 0 entao
         X <- X + 1
      fimse

      Soma <- 5 * x + 20
      escreval("SOMA = ", soma)
      
       escreva("Digite um numero inteiro:")
       leia(X)

  fimenquanto
   

Fimalgoritmo