Algoritmo "Teste_entrada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2021
Var
x, y, z, a, b, c, d : real


Inicio
x <- 2
y <- 3
z <- -7

a <- exp(x,y)
b <- RaizQ(y)
c <- Pi
d <- Abs(z)

  escreval(a)
  escreval(b)
  escreval(c)
  escreval(d)
Fimalgoritmo